#!/bin/bash
# Quick setup helper for GitHub Pages deployment

echo "🦊 Arcadian Media - Telegram Web App Setup Helper"
echo "=================================================="
echo ""
echo "📋 Files ready for GitHub Pages:"
echo "Location: /home/node/.openclaw/workspace/cyberpunk_dashboard/github_pages_files/"
echo ""
echo "📁 Files to upload:"
ls -la /home/node/.openclaw/workspace/cyberpunk_dashboard/github_pages_files/
echo ""
echo "🔗 Expected URL after setup:"
echo "https://lolawhite888.github.io/arcadian-media/"
echo ""
echo "🚀 Quick Setup:"
echo "1. Create repo: https://github.com/new"
echo "   Name: arcadian-media"
echo "   Public: ✓"
echo "   No README: ✓"
echo ""
echo "2. Upload ALL 3 files from github_pages_files/"
echo ""
echo "3. Enable Pages:"
echo "   Settings → Pages → main branch → / (root)"
echo ""
echo "4. Test URL (wait 1-2 minutes)"
echo ""
echo "5. Send me the URL to configure Telegram bot!"
echo ""
echo "🎯 Result: One-tap dashboard in your morning briefing!"