-- EMMA - Supabase Tables
-- Copy and paste this entire script into Supabase SQL Editor (Dashboard > SQL Editor)

-- === LEADS TABLE ===
CREATE TABLE IF NOT EXISTS leads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_name TEXT NOT NULL,
  company_number TEXT,
  website TEXT,
  industry TEXT,
  description TEXT,
  email TEXT,
  phone TEXT,
  address TEXT,
  postcode TEXT,
  city TEXT,
  county TEXT,
  country TEXT DEFAULT 'United Kingdom',
  linkedin_url TEXT,
  facebook_url TEXT,
  twitter_url TEXT,
  estimated_revenue TEXT,
  employee_count TEXT,
  source TEXT DEFAULT 'manual',
  status TEXT DEFAULT 'new' CHECK (status IN ('new','contacted','qualified','rejected','converted')),
  notes TEXT,
  enriched BOOLEAN DEFAULT false,
  enriched_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- === CAMPAIGNS TABLE ===
CREATE TABLE IF NOT EXISTS campaigns (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  status TEXT DEFAULT 'draft' CHECK (status IN ('draft','active','paused','completed')),
  target_industry TEXT,
  target_location TEXT,
  target_size TEXT,
  email_template TEXT,
  leads_count INTEGER DEFAULT 0,
  sent_count INTEGER DEFAULT 0,
  reply_count INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- === CAMPAIGN LEADS JUNCTION TABLE ===
CREATE TABLE IF NOT EXISTS campaign_leads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campaign_id BIGINT REFERENCES campaigns(id) ON DELETE CASCADE,
  lead_id BIGINT REFERENCES leads(id) ON DELETE CASCADE,
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending','sent','replied','bounced','converted')),
  emailed_at TIMESTAMPTZ,
  replied_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(campaign_id, lead_id)
);

-- === API LOGS TABLE ===
CREATE TABLE IF NOT EXISTS api_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  endpoint TEXT,
  method TEXT,
  status_code INTEGER,
  duration_ms INTEGER,
  ip_address TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- === SETTINGS TABLE ===
CREATE TABLE IF NOT EXISTS settings (
  key TEXT PRIMARY KEY,
  value TEXT,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Insert default settings
INSERT INTO settings (key, value) VALUES
  ('access_code', '@TONY2026'),
  ('agent_name', 'Emma'),
  ('company', 'eco-emma.com'),
  ('telegram_notifications', 'true')
ON CONFLICT (key) DO NOTHING;

-- === INDEXES ===
CREATE INDEX IF NOT EXISTS idx_leads_status ON leads(status);
CREATE INDEX IF NOT EXISTS idx_leads_company ON leads(company_name);
CREATE INDEX IF NOT EXISTS idx_leads_source ON leads(source);
CREATE INDEX IF NOT EXISTS idx_campaign_status ON campaigns(status);
CREATE INDEX IF NOT EXISTS idx_campaign_leads_status ON campaign_leads(status);

-- === AUTO-UPDATE TRIGGER ===
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'update_leads_updated_at') THEN
    CREATE TRIGGER update_leads_updated_at BEFORE UPDATE ON leads FOR EACH ROW EXECUTE FUNCTION update_updated_at();
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'update_campaigns_updated_at') THEN
    CREATE TRIGGER update_campaigns_updated_at BEFORE UPDATE ON campaigns FOR EACH ROW EXECUTE FUNCTION update_updated_at();
  END IF;
END $$;

-- === ROW LEVEL SECURITY ===
ALTER TABLE leads ENABLE ROW LEVEL SECURITY;
ALTER TABLE campaigns ENABLE ROW LEVEL SECURITY;
ALTER TABLE campaign_leads ENABLE ROW LEVEL SECURITY;
ALTER TABLE api_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE settings ENABLE ROW LEVEL SECURITY;

-- Allow all operations with service_role key
CREATE POLICY "Service role can do everything on leads" ON leads FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Service role can do everything on campaigns" ON campaigns FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Service role can do everything on campaign_leads" ON campaign_leads FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Service role can do everything on api_logs" ON api_logs FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Service role can do everything on settings" ON settings FOR ALL USING (true) WITH CHECK (true);
