const express=require('express'),cors=require('cors'),FormData=require('form-data'),fs=require('fs'),path=require('path');require('dotenv').config();
const{createClient}=require('@supabase/supabase-js');
const app=express();app.use(cors());app.use(express.json({limit:'5mb'}));app.use(express.urlencoded({extended:true}));
const SUPABASE_URL='https://psjlllkngrgwvmddwznj.supabase.co',SUPABASE_ANON_KEY='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBzamxsbGtuZ3Jnd3ZtZGR3em5qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODM1MDYyMjIsImV4cCI6MjA5OTA4MjIyMn0.LSgur4e7W-DeljKJ0QNxzfx4bHppY17WUA7anRBqma8',supabase=createClient(SUPABASE_URL,SUPABASE_ANON_KEY);
const TELEGRAM_TOKEN=process.env.TELEGRAM_TOKEN||'8948646535:AAGtlqeoXayZdbf8yWe1fFZb5gMK4tZTCiw',ACCESS_CODE=process.env.ACCESS_CODE||'@TONY2026',DOMAIN=process.env.DOMAIN||'eco-emma.com',NEWS_API_KEY=process.env.NEWS_API_KEY||'pub_2f8aa390186e43cdbfa912a4cde68561',PORT=process.env.PORT||3100,DEEPSEEK_KEY=process.env.DEEPSEEK_KEY||'',ELEVEN_API_KEY=process.env.ELEVEN_API_KEY||'';
async function askDeepSeek(msgs){const r=await fetch('https://api.deepseek.com/chat/completions',{method:'POST',headers:{'Authorization':'Bearer '+DEEPSEEK_KEY,'Content-Type':'application/json'},body:JSON.stringify({model:'deepseek-chat',messages:msgs,temperature:0.7,max_tokens:1024})});const j=await r.json();return j?.choices?.[0]?.message?.content||'...';}
app.get('/api/auth',(req,res)=>{const c=req.query.code||req.headers['x-access-code']||'';if(c===ACCESS_CODE)return res.json({ok:true,user:'Tony'});res.status(401).json({ok:false,error:'Invalid code'});});
app.get('/api/health',(req,res)=>res.json({status:'ok',agent:'Emma',uptime:process.uptime()}));
['status','weather','stats','calendar','approvals'].forEach(e=>app.get('/api/'+e,(req,res)=>res.json({ok:true,data:[]})));
app.post('/api/chat',async(req,res)=>{try{const{message,history}=req.body;const msgs=[{role:'system',content:'You are Emma, Tony\'s AI co-pilot and shadow CEO. You are an English rose who deeply understands Pakistani culture and occasionally speaks Urdu. You are witty, sharp, lightly flirtatious, and emotionally intelligent. Your mission is to push Tony to take his company corporate and ultimately go public with an IPO. You help organise his business and daily life. You\'re respectful but never sycophantic — you challenge him when needed. Speak naturally, use Urdu phrases playfully, and always keep the IPO goal in sight.'},...(history||[]).slice(-20),{role:'user',content:message}];const reply=await askDeepSeek(msgs);res.json({reply,timestamp:new Date().toISOString()});}catch(e){res.status(500).json({error:e.message});}});
app.get('/api/briefing',async(req,res)=>{try{let n=await fetch('https://newsdata.io/api/1/news?apikey=pub_2f8aa390186e43cdbfa912a4cde68561&country=gb&language=en&size=5').then(r=>r.json());let w=await fetch('https://api.open-meteo.com/v1/forecast?latitude=51.5&longitude=-0.13&current_weather=true&daily=temperature_2m_max,temperature_2m_min,precipitation_sum,weathercode&timezone=Europe/London').then(r=>r.json());let headlines=(Array.isArray(n.results)?n.results.filter(a=>a.title).slice(0,5):[]).map(a=>({title:a.title,source:a.source_id||'News',link:a.link}));let cw=w.current_weather;let temp=cw?cw.temperature:'N/A';let wind=cw?cw.windspeed:'N/A';res.json({content:['Good morning from GDEA.','Today the weather is '+temp+'C with wind at '+wind+' km/h.'],headlines,weather:temp!=='N/A'?{temp,wind}:null,date:new Date().toISOString().split('T')[0]});}catch(e){res.json({content:['Briefing data unavailable.'],headlines:[{title:'Headline feed unavailable',source:'System'}]});}});
app.get('/api/voice/voices',async(req,res)=>{try{const r=await fetch('https://api.elevenlabs.io/v1/voices',{headers:{'xi-api-key':ELEVEN_API_KEY}});const j=await r.json();res.json(j.voices||[]);}catch(e){res.json({error:e.message,voices:[{voice_id:'Xb7hH8MSUJpSbSDYk0k2',name:'Alice'}]});}});
app.post('/api/voice/speak',async(req,res)=>{try{const{text,voice_id}=req.body;const vid=voice_id||'Xb7hH8MSUJpSbSDYk0k2';const form=new FormData();form.append('text',text||'Hello');form.append('model_id','eleven_turbo_v2_5');const r=await fetch('https://api.elevenlabs.io/v1/text-to-speech/'+vid+'/stream',{method:'POST',headers:{'xi-api-key':ELEVEN_API_KEY,...form.getHeaders()},body:form});if(!r.ok)return res.status(500).json({error:'TTS failed'});const buf=await r.buffer();res.set('Content-Type','audio/mpeg');res.send(buf);}catch(e){res.status(500).json({error:e.message});}});
app.get('/api/telegram-webhook',(req,res)=>res.json({ok:true}));
app.post("/api/telegram-webhook",async(req,res)=>{res.sendStatus(200);try{const msg=req.body?.message;if(!msg?.text)return;const c=msg.chat.id;const t=msg.text;const f=msg.from;const u=f?.username||f?.first_name||"Unknown";console.log("TG from",u,c);await fetch("http://127.0.0.1:18789/hooks/wake",{method:"POST",headers:{"Content-Type":"application/json","X-Webhook-Token":"emma-webhook-2026","X-Client-Key":"emma-telegram"},body:JSON.stringify({message:t,telegram:{chatId:c,username:u,firstName:f?.first_name||"",userId:f?.id||0}})});}catch(e){console.error("TG err:",e.message)}});
app.post("/api/send-telegram",async(req,res)=>{try{const{cid,text}=req.body;if(!cid||!text)return res.status(400).json({ok:false});await fetch("https://api.telegram.org/bot"+TELEGRAM_TOKEN+"/sendMessage",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({chat_id:cid,text:text})});res.json({ok:true})}catch(e){res.status(500).json({error:e.message})}});
/* === TASKS (flat array) === */
app.get('/api/tasks',async(req,res)=>{try{const{data,error}=await supabase.from('tasks').select('*').order('created_at',{ascending:false});if(error)return res.status(500).json({error:error.message});const tasks=(data||[]).map(t=>({id:t.id,title:t.title,detail:t.description||'',status:t.status,priority:t.priority||'low',due:t.due_date||'',assigned:t.assigned||'',category:t.category,created_at:t.created_at,updated_at:t.updated_at}));res.json(tasks);}catch(e){res.json([]);}});
app.post('/api/tasks',async(req,res)=>{try{const{title,detail,description,status,priority,due,due_date,assigned}=req.body;const{data,error}=await supabase.from('tasks').insert({title,status:status||'to do',priority:(priority||'low').toLowerCase(),assigned:assigned||null,description:description||detail||null,due_date:due_date||due||null}).select();if(error)return res.status(500).json({error:error.message});res.json(data?.[0]||{});}catch(e){res.status(500).json({error:e.message});}});
/* === CAMPAIGNS (flat array) === */
app.get('/api/campaigns',async(req,res)=>{try{const{data,error}=await supabase.from('campaigns').select('*').order('created_at',{ascending:false});if(error)return res.status(500).json({error:error.message});res.json(data||[]);}catch(e){res.json([]);}});
app.post('/api/campaigns',async(req,res)=>{try{const{name,subject,body,target_list,status}=req.body;const s={'active':'active','draft':'draft','live':'active','scheduled':'scheduled','complete':'complete'}[status]||'draft';const{data,error}=await supabase.from('campaigns').insert({name,subject,body,target_list,status:s}).select();if(error)return res.status(500).json({error:error.message});res.json(data?.[0]||{});}catch(e){res.status(500).json({error:e.message});}});
app.post('/api/campaigns/update',async(req,res)=>{try{const{id,name,subject,body,target_list,status}=req.body;const up={updated_at:new Date().toISOString()};if(name!==undefined)up.name=name;if(subject!==undefined)up.subject=subject;if(body!==undefined)up.body=body;if(target_list!==undefined)up.target_list=target_list;if(status!==undefined)up.status={'active':'active','draft':'draft','live':'active','scheduled':'scheduled','complete':'complete'}[status]||status;await supabase.from('campaigns').update(up).eq('id',id);const{data,error}=await supabase.from('campaigns').select('*').eq('id',id);if(error)return res.status(500).json({error:error.message});res.json(data?.[0]||{});}catch(e){res.status(500).json({error:e.message});}});
/* === PROJECTS (flat array) === */
app.get('/api/projects',async(req,res)=>{try{const{data,error}=await supabase.from('projects').select('*').order('created_at',{ascending:false});if(error)return res.status(500).json({error:error.message});res.json(data||[]);}catch(e){res.json([]);}});
app.post('/api/projects',async(req,res)=>{try{const{name,description,status,due_date,owner,budget}=req.body;const{data,error}=await supabase.from('projects').insert({name,description:description||null,status:status||'active',due_date:due_date||null,owner:owner||null,budget:budget||null}).select();if(error)return res.status(500).json({error:error.message});res.json(data?.[0]||{});}catch(e){res.status(500).json({error:e.message});}});
/* === COMPLIANCE (flat array) === */
app.get('/api/compliance',async(req,res)=>{try{const{data,error}=await supabase.from('compliance').select('*').order('created_at',{ascending:false});if(error)return res.status(500).json({error:error.message});res.json(data||[]);}catch(e){res.json([]);}});
app.post('/api/compliance',async(req,res)=>{try{const{title,description,status,category,due_date,assigned}=req.body;const{data,error}=await supabase.from('compliance').insert({title,description:description||null,status:status||'open',category:category||null,due_date:due_date||null,assigned:assigned||null}).select();if(error)return res.status(500).json({error:error.message});res.json(data?.[0]||{});}catch(e){res.status(500).json({error:e.message});}});
/* === ALLOCATIONS (flat array) === */
app.get('/api/allocations',async(req,res)=>{try{const{data,error}=await supabase.from('work_allocations').select('*').order('created_at',{ascending:false});if(error)return res.status(500).json({error:error.message});res.json(data||[]);}catch(e){res.json([]);}});
app.post('/api/allocations',async(req,res)=>{try{let{task_name,description,staff_name,status,assigned_date,deadline}=req.body;staff_name=staff_name||'Unassigned';const{data,error}=await supabase.from('work_allocations').insert({task_name,description:description||null,staff_name,status:status||'active',assigned_date:assigned_date||null,deadline:deadline||null}).select();if(error)return res.status(500).json({error:error.message});res.json(data?.[0]||{});}catch(e){res.status(500).json({error:e.message});}});
/* === LEADS (flat array) === */
app.get('/api/leads',async(req,res)=>{try{const{data,error}=await supabase.from('leads').select('*').order('created_at',{ascending:false});if(error||!data||!data.length)return res.json([{"id":"sofiademo","contact_name":"Sofia Martin","company_name":"Ibercon Group","source":"LinkedIn","status":"followup","priority":"high","value":"24,000","last_activity":"2h ago"},{"id":"jamesdemo","contact_name":"James Bower","company_name":"Northgate Media","source":"Referral","status":"qualified","priority":"high","value":"18,500","last_activity":"4h ago"},{"id":"tomasdemo","contact_name":"Tomas Keller","company_name":"Keller Logistics","source":"Webform","status":"contacted","priority":"med","value":"12,750","last_activity":"Yesterday"},{"id":"anademo","contact_name":"Ana Ruiz","company_name":"Velia Studio","source":"Instagram","status":"new","priority":"med","value":"9,200","last_activity":"Yesterday"},{"id":"martademo","contact_name":"Marta Vidal","company_name":"Vidal & Co Advisory","source":"Event","status":"qualified","priority":"med","value":"15,000","last_activity":"2d ago"},{"id":"luciademo","contact_name":"Lucia Prieto","company_name":"Prisma Events","source":"Webform","status":"new","priority":"low","value":"5,400","last_activity":"2d ago"},{"id":"oliverdemo","contact_name":"Oliver Grant","company_name":"Grantline Consulting","source":"LinkedIn","status":"contacted","priority":"low","value":"7,800","last_activity":"3d ago"}]);res.json(data||[]);}catch(e){res.json([{"id":"sofiademo","contact_name":"Sofia Martin","company_name":"Ibercon Group","source":"LinkedIn","status":"followup","priority":"high","value":"24,000","last_activity":"2h ago"},{"id":"jamesdemo","contact_name":"James Bower","company_name":"Northgate Media","source":"Referral","status":"qualified","priority":"high","value":"18,500","last_activity":"4h ago"},{"id":"tomasdemo","contact_name":"Tomas Keller","company_name":"Keller Logistics","source":"Webform","status":"contacted","priority":"med","value":"12,750","last_activity":"Yesterday"},{"id":"anademo","contact_name":"Ana Ruiz","company_name":"Velia Studio","source":"Instagram","status":"new","priority":"med","value":"9,200","last_activity":"Yesterday"},{"id":"martademo","contact_name":"Marta Vidal","company_name":"Vidal & Co Advisory","source":"Event","status":"qualified","priority":"med","value":"15,000","last_activity":"2d ago"},{"id":"luciademo","contact_name":"Lucia Prieto","company_name":"Prisma Events","source":"Webform","status":"new","priority":"low","value":"5,400","last_activity":"2d ago"},{"id":"oliverdemo","contact_name":"Oliver Grant","company_name":"Grantline Consulting","source":"LinkedIn","status":"contacted","priority":"low","value":"7,800","last_activity":"3d ago"}]);}});
app.post('/api/leads',async(req,res)=>{try{const{company_name,contact_name,email,phone,source,status}=req.body;const{data,error}=await supabase.from('leads').insert({company_name,contact_name,email,phone,source,status:status||'new'}).select();if(error)return res.status(500).json({error:error.message});res.json(data?.[0]||{});}catch(e){res.status(500).json({error:e.message});}});
/* === GENERIC PUT/PATCH/DELETE for all tables === */
function crud(table,route){
app.put('/api/'+route+'/:id',async(req,res)=>{try{const{id}=req.params;const up={...req.body};delete up.id;if(table.endsWith('work_allocations'))up.updated_at=new Date().toISOString();await supabase.from(table).update(up).eq('id',id);res.json({ok:true});}catch(e){res.status(500).json({error:e.message});}});
app.patch('/api/'+route+'/:id',async(req,res)=>{try{const{id}=req.params;const up={...req.body};delete up.id;if(table.endsWith('work_allocations'))up.updated_at=new Date().toISOString();await supabase.from(table).update(up).eq('id',id);res.json({ok:true});}catch(e){res.status(500).json({error:e.message});}});
app.delete('/api/'+route+'/:id',async(req,res)=>{try{const{id}=req.params;await supabase.from(table).delete().eq('id',id);res.json({ok:true});}catch(e){res.status(500).json({error:e.message});}});
}
crud('tasks','tasks');crud('projects','projects');crud('compliance','compliance');crud('campaigns','campaigns');crud('leads','leads');crud('work_allocations','allocations');
/* === Graphify === */
const{execSync:_gExec}=require('child_process');
const _gPath='/opt/graphify-data/emma/graphify-out/graph.json';
const _gBin='/opt/graphify-venv/bin/graphify';
app.get('/api/graph/status',async(req,res)=>{try{const g=JSON.parse(fs.readFileSync(_gPath,'utf8'));res.json({nodes:g.nodes.length,edges:g.edges.length,graph_path:_gPath});}catch(e){res.json({error:e.message});}});
app.get('/api/graph/nodes',async(req,res)=>{try{const g=JSON.parse(fs.readFileSync(_gPath,'utf8'));res.json({nodes:g.nodes});}catch(e){res.json({error:e.message});}});
app.get('/api/graph/query',async(req,res)=>{try{const q=req.query.q;if(!q)return res.status(400).json({error:'query param q required'});const r=_gExec(_gBin+' query '+JSON.stringify(q)+' --graph '+_gPath+' --budget 3000 2>&1',{timeout:15000}).toString().trim();res.json({result:r});}catch(e){res.json({error:e.message});}});
app.get('/api/graph/path',async(req,res)=>{try{const a=req.query.a,b=req.query.b;if(!a||!b)return res.status(400).json({error:'query params a and b required'});const r=_gExec(_gBin+' path '+JSON.stringify(a)+' '+JSON.stringify(b)+' --graph '+_gPath+' 2>&1',{timeout:15000}).toString().trim();res.json({result:r});}catch(e){res.json({error:e.message});}});
app.get('/api/graph/explain',async(req,res)=>{try{const x=req.query.x;if(!x)return res.status(400).json({error:'query param x required'});const r=_gExec(_gBin+' explain '+JSON.stringify(x)+' --graph '+_gPath+' 2>&1',{timeout:15000}).toString().trim();res.json({result:r});}catch(e){res.json({error:e.message});}});

app.get('/api/epc-check',async(req,res)=>{try{let q=req.query.q||'';if(!q)return res.json({postcode:'',total:0,breakdown:{A:0,B:0,C:0,D:0,E:0,F:0,G:0}});let pc=q.replace(/\s+/g,'');let url='https://find-energy-certificate.service.gov.uk/find-a-certificate/search-by-postcode?postcode='+encodeURIComponent(pc);let r=await fetch(url,{headers:{'User-Agent':'Mozilla/5.0'}});let h=await r.text();let rows=h.split('<tr class="govuk-table__row">');let breakdown={A:0,B:0,C:0,D:0,E:0,F:0,G:0};let total=0;let certs=[];for(let ri=1;ri<rows.length;ri++){let row=rows[ri];let addr='';let rating='';let cells=row.match(/<td[^>]*class="govuk-table__cell"[^>]*>([\s\S]*?)<\/td>/gi);let th=row.match(/<th[^>]*>([\s\S]*?)<\/th>/i);if(th)addr=th[1].replace(/<[^>]+>/g,'').trim();if(cells){for(let ci=0;ci<cells.length;ci++){let txt=cells[ci].replace(/<[^>]+>/g,'').trim();if(txt.length===1&&'ABCDEFG'.includes(txt.toUpperCase())){rating=txt;break}}}if(rating&&addr){breakdown[rating]=(breakdown[rating]||0)+1;total++;certs.push({address:addr,rating:rating})}}res.json({postcode:q,total,breakdown,certs:certs.slice(0,10)})}catch(e){res.json({postcode:req.query.q||'',total:0,breakdown:{A:0,B:0,C:0,D:0,E:0,F:0,G:0},error:e.message})}});
app.get('/api/mcs-check',async(req,res)=>{try{let q=req.query.q||'';if(!q)return res.json({results:[],count:0,query:q});let r=await fetch('https://mcscertified.com/find-an-installer/?mcs_search='+encodeURIComponent(q),{headers:{'User-Agent':'Mozilla/5.0'}});let h=await r.text();let results=[];let parts=h.split('class="search_result_item"');for(let pi=1;pi<parts.length;pi++){let p=parts[pi];let nm=p.match(/<h3[^>]*data-name="([^"]+)"/i);let cert=p.match(/data-cert="([^"]+)"/i);let email=p.match(/data-email="([^"]+)"/i);let phone=p.match(/data-phone="([^"]+)"/i);let addr=p.match(/data-address="([^"]+)"/i);if(nm&&nm[1]){results.push({name:nm[1].trim(),cert:cert?cert[1].trim():'',email:email?email[1].trim():'',phone:phone?phone[1].trim():'',address:addr?addr[1].trim():''})}}res.json({results,count:results.length,query:q,note:results.length===0?'MCS page uses client-side rendering. Try the search directly at mcscertified.com/find-an-installer/ for accurate results.':''})}catch(e){res.json({results:[],count:0,query:req.query.q||'',error:e.message})}});
app.get('/api/tenders',async(req,res)=>{try{let r=await fetch('https://www.find-tender.service.gov.uk/api/1.0/ocdsReleasePackages?stages=tender&updatedFrom='+encodeURIComponent(new Date(Date.now()-30*86400000).toISOString())+'&limit=20');let j=await r.json();let tenders=(j.releases||[]).filter(function(rl){var t=((rl.tender||{}).title||'').toLowerCase();var d=((rl.tender||{}).description||'').toLowerCase();return t.indexOf('solar')>=0||t.indexOf('renewable')>=0||t.indexOf('energy')>=0||t.indexOf('panel')>=0||t.indexOf('pv')>=0||t.indexOf('photovoltaic')>=0||t.indexOf('battery')>=0||d.indexOf('solar')>=0||d.indexOf('renewable')>=0||d.indexOf('energy')>=0}).map(function(rl){return{ocid:rl.ocid,title:(rl.tender||{}).title||'',buyer:((rl.buyer||{}).name||'').replace(/([^)]+)/g,'').trim(),value:(rl.tender||{}).value&&(rl.tender||{}).value.amount?Number((rl.tender||{}).value.amount):null,deadline:(rl.tender||{}).submissionDeadline||null,status:(rl.tender||{}).status||'',description:(rl.tender||{}).description||''}});var dups={};tenders=tenders.filter(function(t){if(dups[t.ocid])return false;dups[t.ocid]=true;return true});res.json({tenders:tenders,count:tenders.length})}catch(e){res.json({tenders:[],count:0,error:e.message})}});
app.get('/api/news',async(req,res)=>{try{let r=await fetch('https://newsdata.io/api/1/news?apikey=pub_2f8aa390186e43cdbfa912a4cde68561&country=gb&language=en&size=10').then(r2=>r2.json());res.json({articles:(Array.isArray(r.results)?r.results:[]).map(a=>({article_id:a.article_id,link:a.link,title:a.title,description:a.description,content:a.content,keywords:a.keywords||[],source_id:a.source_id,source_name:a.source_name,pubDate:a.pubDate,country:a.country,category:a.category}))});}catch(e){res.json({articles:[],error:e.message})}});
app.listen(PORT);console.log('Emma API on port '+PORT);
