server {
    listen 80;
    listen [::]:80;
    server_name fight.thenewworldorder.io;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name fight.thenewworldorder.io;

    ssl_certificate /etc/letsencrypt/live/thenewworldorder.io/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/thenewworldorder.io/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    root /var/www/fight;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}
