#!/usr/bin/env python3
"""Generate 60+ ad pages across 6 sites. Run on the IONOS server."""
import os, json, base64

AC = 'ca-pub-9534114738328693'
S = { # slots
  'coupn.uk':('7029255420','8504468716','5627023935'),
  'toolstack.uk':('5772014074',),
  'uk-cbdc.co.uk':('8316766455',),
  'pdfoomph.com':('3908268067','6893524050'),
  'isitdownrightnow.co.uk':('1751358101','7699643185'),
  'cheapfind.uk':('3525124687','8125194764'),
}
D = {d:d for d in S}
SKM = '<script type="text/javascript" src="https://s.skimresources.com/js/303631X1791683.skimlinks.js"></script>'
ADJS = '<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client='+AC+'" crossorigin="anonymous"></script>'

def ads(slot):
  return f'''<div class="aw"><ins class="adsbygoogle" style="display:block" data-ad-client="{AC}" data-ad-slot="{slot}" data-ad-format="auto" data-full-width-responsive="true"></ins><script>(adsbygoogle=window.adsbygoogle||[]).push({});</script></div>'''

def page(dom, slug, t, d, k, style, nav, main):
  slots, canon = S[dom], f'https://www.{dom}/{slug}'
  ld = json.dumps({"@context":"https://schema.org","@type":"WebPage","name":t,"description":d,"url":canon,"breadcrumb":{"@type":"BreadcrumbList","itemListElement":[{"@type":"ListItem","position":1,"name":"Home","item":"https://www."+dom+"/"},{"@type":"ListItem","position":2,"name":t,"item":canon}]}})
  return f'''<!DOCTYPE html><html lang=en-GB><head><meta charset=UTF-8><meta name=viewport content="width=device-width,initial-scale=1"><title>{t}</title><meta name=description content="{d}"><meta name=keywords content="{k}"><meta name=robots content="index,follow,max-snippet:-1,max-image-preview:large"><link rel=canonical href="{canon}"><meta property=og:title content="{t}"><meta property=og:description content="{d}"><meta property=og:url content="{canon}"><meta property=og:type content=website><meta property=og:site_name content="{t.split('|')[0].strip()}"><meta property=og:locale content=en_GB><meta name=twitter:card content=summary_large_image><meta name=twitter:title content="{t}"><meta name=twitter:description content="{d}"><meta name=google-adsense-account content={AC}>{ADJS}<script type=application/ld+json>{ld}</script><style>{style}</style></head><body>{nav}{ads(slots[0])}<div class=co>{main}</div>{ads(slots[1]) if len(slots)==3 else ''}{ads(slots[-1])}<footer>(c) 2026 {dom} — <a href=/>Home</a></footer>{SKM}</body></html>'''

def w(dom, pages):
  d = f'/var/www/{D[dom]}/public'
  c = 0
  for slug,t,desc,kw,main in pages:
    with open(f'{d}/{slug}','w') as f:
      f.write(page(dom,slug,t,desc,kw,ST[dom],NV[dom],main))
    c+=1
    print(f'  {slug}')
  print(f'  => {c} pages ({d}/)')

# Styles (compressed)
ST = {}
ST['coupn.uk']='*{margin:0;padding:0;box-sizing:border-box}body{font-family:-apple-system,system-ui,Segoe UI,sans-serif;background:#f0fdf4;color:#1a1a2e;line-height:1.7}.nav{background:linear-gradient(135deg,#059669,#10b981);color:#fff;padding:20px;text-align:center}.nav h1{font-size:1.6em;font-weight:800}.hero{background:linear-gradient(135deg,#059669,#10b981);color:#fff;padding:40px 20px;text-align:center}.hero h2{font-size:2.2em;font-weight:800;margin-bottom:8px}.co{max-width:900px;margin:0 auto;padding:20px}.co h2{color:#059669;margin:25px 0 12px;font-size:1.4em}.co h3{color:#1a1a2e;margin:20px 0 10px}.co p{margin-bottom:14px;color:#444}.co ul,.co ol{margin:10px 0 20px 25px}.co li{margin-bottom:8px;color:#555}.cd{background:#fff;border-radius:14px;padding:30px;box-shadow:0 2px 16px rgba(0,0,0,.06);margin-bottom:20px}.inf{background:#fef3c7;border-radius:8px;padding:14px;margin:15px 0;border-left:4px solid #f59e0b}.bl{display:inline-block;margin:20px 0;background:#059669;color:#fff;padding:10px 20px;border-radius:8px;font-weight:600;text-decoration:none}.aw{max-width:728px;margin:20px auto;min-height:90px}footer{text-align:center;padding:30px;color:#888;font-size:.85em;border-top:1px solid #e5e7eb}footer a{color:#059669;text-decoration:none}@media(max-width:600px){.hero h2{font-size:1.6em}}'
ST['toolstack.uk']='*{margin:0;padding:0;box-sizing:border-box}body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif;background:#f0f2f5;color:#333;line-height:1.7}.nav{text-align:center;padding:40px 20px 20px}.nav h1{font-size:2.5rem;color:#1a1a2e}.nav h1 s{background:linear-gradient(135deg,#4a4a8a,#6a3bb8);-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text}.co{max-width:900px;margin:0 auto;padding:20px}.co h2{color:#4a4a8a;margin:25px 0 12px}.co h3{color:#1a1a2e;margin:20px 0 10px}.co p{margin-bottom:14px;color:#444}.co ul,.co ol{margin:10px 0 20px 25px}.co li{margin-bottom:8px;color:#555}.cd{background:#fff;border-radius:12px;padding:30px;margin:20px 0;box-shadow:0 2px 8px rgba(0,0,0,.06)}.cb{background:#f8f4ff;border:2px solid #6a3bb8;border-radius:12px;padding:24px;margin:20px 0}.cb label{display:block;font-weight:600;margin:10px 0 4px}.cb input,.cb select{width:100%;padding:10px;border:2px solid #ddd;border-radius:8px;font-size:1em}.cb button{background:linear-gradient(135deg,#4a4a8a,#6a3bb8);color:#fff;border:none;padding:12px 24px;border-radius:8px;font-weight:700;cursor:pointer;margin-top:14px}.cr{background:#e8f4e8;padding:16px;border-radius:8px;margin-top:12px;font-size:1.1em;font-weight:700;color:#2e7d32;display:none;line-height:1.8}.co table{width:100%;border-collapse:collapse;margin:15px 0}.co th,.co td{padding:10px;border:1px solid #e0e0e0;text-align:left}.co th{background:#f0f2f5;font-weight:600}.bl{display:inline-block;margin:20px 0;background:linear-gradient(135deg,#4a4a8a,#6a3bb8);color:#fff;padding:10px 20px;border-radius:8px;font-weight:600;text-decoration:none}.aw{max-width:728px;margin:20px auto;min-height:90px}footer{background:linear-gradient(135deg,#1a1a2e,#3a1a6e);color:#ccc;text-align:center;padding:24px;margin-top:20px;font-size:.85rem}footer a{color:#a8a8ff;text-decoration:none}@media(max-width:600px){.nav h1{font-size:1.8rem}}'
ST['uk-cbdc.co.uk']='*{margin:0;padding:0;box-sizing:border-box}body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif;background:#f8f9fa;color:#333;line-height:1.7}a{color:#4facfe;text-decoration:none}.nav{background:#fff;border-bottom:1px solid #e8ecf1;position:sticky;top:0;z-index:1000;height:64px;display:flex;align-items:center;justify-content:space-between;padding:0 24px;max-width:1100px;margin:0 auto}.nav .lg{font-weight:700;background:linear-gradient(135deg,#4facfe 0%,#00f2fe 100%);-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text}.nav .lk{display:flex;gap:8px}.nav .lk a{color:#333;font-size:.9rem;padding:8px 14px;border-radius:8px}.nav .lk a:hover{background:#eef2ff;color:#4facfe}.hero{background:linear-gradient(135deg,#667eea 0%,#764ba2 100%);text-align:center;padding:60px 24px 50px}.hero h1{font-size:2.2rem;font-weight:800;color:#fff;margin-bottom:12px}.hero p{font-size:1.05rem;color:rgba(255,255,255,.85);max-width:650px;margin:0 auto}.co{max-width:900px;margin:0 auto;padding:20px}.co h2{color:#667eea;margin:28px 0 14px}.co h3{color:#333;margin:20px 0 10px}.co p{margin-bottom:14px;color:#444}.co ul,.co ol{margin:10px 0 20px 25px}.co li{margin-bottom:8px;color:#555}.co table{width:100%;border-collapse:collapse;margin:15px 0}.co th,.co td{padding:10px;border:1px solid #e0e0e0;text-align:left}.co th{background:#f0f2f5;font-weight:600}.cd{background:#fff;border:1px solid #e8ecf1;border-radius:12px;padding:32px;margin:30px 0;box-shadow:0 2px 10px rgba(0,0,0,.08)}.ib{background:#f0f7ff;border-left:4px solid #4facfe;padding:16px 20px;margin:15px 0;border-radius:0 8px 8px 0}.bl{display:inline-block;margin:20px 0;background:linear-gradient(135deg,#667eea 0%,#764ba2 100%);color:#fff;padding:10px 20px;border-radius:8px;font-weight:600;text-decoration:none}.aw{max-width:728px;margin:20px auto;min-height:90px}footer{background:#1a1f36;color:#b0b8c8;padding:40px 24px;text-align:center}footer p{font-size:.85rem;color:#6b7488}@media(max-width:768px){.hero h1{font-size:1.6rem}}'
ST['pdfoomph.com']='*{margin:0;padding:0;box-sizing:border-box}body{font-family:-apple-system,system-ui,"Segoe UI",sans-serif;background:#f8fafc;color:#1a1a2e;line-height:1.7}.nav{background:linear-gradient(135deg,#f093fb 0%,#f5576c 100%);color:#fff;padding:16px 0;text-align:center}.nav h1{font-size:1.4em;font-weight:800}.hero{background:linear-gradient(135deg,#f093fb 0%,#f5576c 100%);color:#fff;padding:50px 20px;text-align:center}.hero h2{font-size:2.2em;font-weight:800;margin-bottom:10px}.hero p{font-size:1.05em;opacity:.9;max-width:560px;margin:0 auto}.co{max-width:900px;margin:0 auto;padding:20px}.co h2{color:#f5576c;margin:25px 0 12px}.co h3{color:#1a1a2e;margin:20px 0 10px}.co p{margin-bottom:14px;color:#444}.co ul,.co ol{margin:10px 0 20px 25px}.co li{margin-bottom:8px;color:#555}.cd{background:#fff;border-radius:16px;padding:32px;box-shadow:0 4px 24px rgba(0,0,0,.08);margin-bottom:30px}.bl{display:inline-block;margin:20px 0;background:linear-gradient(135deg,#f093fb 0%,#f5576c 100%);color:#fff;padding:10px 20px;border-radius:8px;font-weight:600;text-decoration:none}.aw{max-width:728px;margin:20px auto;min-height:90px}footer{text-align:center;padding:30px;color:#888;font-size:.85em;border-top:1px solid #eee}@media(max-width:600px){.hero h2{font-size:1.6em}}'
ST['isitdownrightnow.co.uk']='*{margin:0;padding:0;box-sizing:border-box}body{font-family:-apple-system,system-ui,"Segoe UI",sans-serif;background:#0a0a1a;color:#e0e0f0;line-height:1.7}.nav{background:linear-gradient(135deg,#0f0c29 0%,#302b63 50%,#24243e 100%);padding:20px;text-align:center;border-bottom:1px solid rgba(255,255,255,.1)}.nav h1{font-size:1.5em;font-weight:800}.hero{padding:40px 20px;text-align:center;max-width:700px;margin:0 auto}.hero h2{font-size:2em;font-weight:800;margin-bottom:8px}.hero p{opacity:.7;font-size:1.05em}.co{max-width:800px;margin:0 auto;padding:20px}.co h2{color:#667eea;margin:25px 0 12px}.co h3{color:#e0e0f0;margin:20px 0 10px}.co p{margin-bottom:14px;color:#b0b0d0}.co ul,.co ol{margin:10px 0 20px 25px}.co li{margin-bottom:8px;color:#b0b0d0}.cd{background:#1a1a3a;border:1px solid #3a3a5a;border-radius:12px;padding:28px;margin:20px 0}.bl{display:inline-block;margin:20px 0;background:linear-gradient(135deg,#667eea 0%,#764ba2 100%);color:#fff;padding:10px 20px;border-radius:8px;font-weight:600;text-decoration:none}.aw{max-width:728px;margin:20px auto;min-height:90px}footer{text-align:center;padding:30px;color:#666;font-size:.85em;border-top:1px solid #3a3a5a}@media(max-width:600px){.hero h2{font-size:1.4em}}'
ST['cheapfind.uk']='*{margin:0;padding:0;box-sizing:border-box}body{font-family:-apple-system,system-ui,"Segoe UI",sans-serif;background:#f8fafc;color:#1a1a2e;line-height:1.7}.nav{background:linear-gradient(135deg,#667eea 0%,#764ba2 100%);color:#fff;padding:20px;text-align:center}.nav h1{font-size:1.6em;font-weight:800}.hero{padding:40px 20px;text-align:center;background:linear-gradient(135deg,#667eea 0%,#764ba2 100%);color:#fff}.hero h2{font-size:2em;font-weight:800;margin-bottom:8px}.hero p{opacity:.9;font-size:1.05em;max-width:500px;margin:0 auto}.co{max-width:900px;margin:0 auto;padding:20px}.co h2{background:linear-gradient(135deg,#667eea 0%,#764ba2 100%);-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text;margin:25px 0 12px}.co h3{color:#1a1a2e;margin:20px 0 10px}.co p{margin-bottom:14px;color:#444}.co ul,.co ol{margin:10px 0 20px 25px}.co li{margin-bottom:8px;color:#555}.cd{background:#fff;border-radius:14px;padding:30px;box-shadow:0 2px 16px rgba(0,0,0,.06);margin-bottom:20px}.dh{background:linear-gradient(135deg,#667eea 0%,#764ba2 100%);color:#fff;border-radius:12px;padding:20px;margin:20px 0;text-align:center}.dh .b{font-size:2em;font-weight:800}.dh .s{opacity:.85;font-size:.9em}.bl{display:inline-block;margin:20px 0;background:linear-gradient(135deg,#667eea 0%,#764ba2 100%);color:#fff;padding:10px 20px;border-radius:8px;font-weight:600;text-decoration:none}.aw{max-width:728px;margin:20px auto;min-height:90px}footer{text-align:center;padding:30px;color:#888;font-size:.85em;border-top:1px solid #eee}@media(max-width:600px){.hero h2{font-size:1.6em}}'

NV = {
  'uk-cbdc.co.uk': '<div class=nav><div class=lg>uk-cbdc.co.uk</div><div class=lk><a href=/>Home</a><a href=/bitcoin-calculator.html>BTC</a><a href=/crypto-profit-calculator.html>Profit</a><a href=/staking-calculator.html>Staking</a></div></div>',
  'pdfoomph.com': '<div class=nav><h1>PDFoomph</h1></div>',
  'isitdownrightnow.co.uk': '<div class=nav><h1>Is It Down Right Now?</h1></div>',
  'toolstack.uk': '<div class=nav><h1>ToolStack UK</h1></div>',
  'coupn.uk': '<div class=nav><h1>Coupn &mdash; Free UK Coupon Codes</h1></div>',
  'cheapfind.uk': '<div class=nav><h1>CheapFind UK &mdash; Best Deals</h1></div>',
}

def h2(h, p):
  return f'<div class=hero><h2>{h}</h2><p>{p}</p></div>'

def cd(html):
  return f'<div class=cd>{html}</div>'


# coupn.uk content
COUPN = [
  ('amazon-deals.html', 'Amazon UK Coupons & Discount Codes | Coupn',
   'Find the best Amazon UK coupon codes and discount vouchers. Save on electronics, fashion, home essentials.',
   'Amazon UK coupon codes, Amazon discount vouchers, Amazon deals UK, Amazon promo codes',
   h2('Amazon UK Deals - Verified Codes','')+cd('''<h2>Latest Amazon UK Coupon Codes - May 2026</h2><p>Amazon UK is one of the best places to shop online. We track the latest discounts daily.</p><h3>Top Deals Right Now</h3><ul><li><strong>Echo Dot (5th Gen)</strong> - 27.99 <s>54.99</s> - Save 49%</li><li><strong>Fire TV Stick 4K</strong> - 29.99 <s>49.99</s> - Save 40%</li><li><strong>Kindle Paperwhite</strong> - 94.99 <s>139.99</s> - Save 32%</li><li><strong>Ring Video Doorbell</strong> - 49.99 <s>89.99</s> - Save 44%</li><li><strong>Amazon Basics 50-pack AAA</strong> - 6.99 <s>11.99</s> - Save 42%</li></ul><h2>How to Use Amazon Promo Codes</h2><ol><li>Add items to your basket</li><li>Proceed to checkout</li><li>Enter the code in Gift cards & vouchers</li><li>Click Apply</li></ol><div class=inf>Subscribe & Save offers extra 5-15% off household essentials.</div><h2>Best Times to Shop on Amazon UK</h2><p>Prime Day (July) and Black Friday (November) offer the biggest discounts. Shop Subscribe & Save to save hundreds per year.</p>''')+cd('''<h2>Amazon UK Shopping Guide</h2><p>Prime members get free one-day delivery on millions of items plus Prime Video, Music and Reading. Non-Prime orders over 25 get free standard delivery.</p><p>Use Amazon price trackers to monitor products and catch the lowest price.</p>''')+'<a href=/ class=bl><- Back to Coupn</a>'),
  ('tesco-coupons.html', 'Tesco UK Coupons & Discount Codes | Coupn',
   'Find Tesco UK discount codes and Clubcard deals. Save money on your weekly grocery shop.',
   'Tesco coupon codes, Tesco discount vouchers, Tesco Clubcard UK, grocery deals UK',
   h2('Tesco Coupons - Verified Weekly','')+cd('''<h2>Latest Tesco UK Coupon Codes - May 2026</h2><p>Tesco is the UK's largest supermarket chain. From Clubcard Prices to fuel vouchers.</p><h3>Clubcard Prices - Best Way to Save</h3><p>Free to join, saves the average household 300+ per year. Exclusive discounts on 8,000+ products.</p><ul><li><strong>Fuel Save</strong> - Up to 5p per litre at Tesco Petrol Stations</li><li><strong>Clubcard Rewards Partners</strong> - 3x value with Pizza Express, LEGOLAND</li><li><strong>Double Points</strong> - Occasional 2x promotions</li></ul><h2>Delivery Saver Pass</h2><p>From 3.99/month for weekday delivery slots. Anytime Saver at 7.99/month for unlimited free delivery.</p><div class=inf>Combine Clubcard Prices with yellow sticker reductions for maximum savings. Evening markdowns from 6pm.</div>''')+'<a href=/ class=bl><- Back to Coupn</a>'),
  ('argos-vouchers.html', 'Argos UK Voucher Codes & Discounts | Coupn',
   'Verified Argos UK voucher codes and discount deals. Save on toys, electronics, furniture.',
   'Argos voucher codes, Argos discount codes, Argos deals UK, Nectar prices Argos',
   h2('Argos Vouchers - Verified Codes','')+cd('''<h2>Latest Argos UK Voucher Codes - May 2026</h2><h3>Current Deals</h3><ul><li><strong>10 off 75+</strong> - Code: SAVE10</li><li><strong>Clearance</strong> - Up to 50% off</li><li><strong>3 for 2</strong> - Selected toys and games</li><li><strong>Free Click & Collect</strong></li></ul><h2>Nectar at Argos</h2><p>Nectar Prices give exclusive discounts for card holders. Earn 1 point per 1.</p>''')+'<a href=/ class=bl><- Back to Coupn</a>'),
  ('asda-discounts.html', 'Asda UK Discount Codes & Grocery Deals | Coupn',
   'Latest Asda UK discount codes and grocery deals. Save money on your Asda shop.',
   'Asda discount codes, Asda grocery deals, Asda Rewards, George clothing deals',
   h2('Asda Discounts - Daily Updates','')+cd('''<h2>Latest Asda UK Deals - May 2026</h2><p>Asda price-matches Aldi and Lidl on hundreds of products automatically.</p><h3>Asda Rewards - Cashpot</h3><p>Build a Cashpot with every shop. Save 50-100 per year.</p><ul><li><strong>George Clothing</strong> - Up to 50% off</li><li><strong>Pizza Counter</strong> - 2 for 8 large pizzas</li><li><strong>Fuel Save</strong> - Up to 2p per litre</li></ul>''')+'<a href=/ class=bl><- Back to Coupn</a>'),
  ('currys-promo-codes.html', 'Currys UK Promo Codes & Tech Deals | Coupn',
   'Best Currys UK promo codes for laptops, TVs, appliances and gaming.',
   'Currys promo codes, Currys discount codes, tech deals UK, Currys price match',
   h2('Currys Promo Codes - Tech Savings','')+cd('''<h2>Latest Currys UK Promo Codes - May 2026</h2><ul><li><strong>100 off laptops over 499</strong> - TECH100</li><li><strong>Free delivery</strong> - Orders over 50</li><li><strong>Student discount</strong> - Up to 10% off</li><li><strong>Clearance</strong> - Up to 30% off</li></ul><h2>Price Match Guarantee</h2><p>Find cheaper at John Lewis, AO, Amazon, Argos, Very, or Richer Sounds? Currys refunds the difference within 7 days.</p><h2>Best Time to Buy Tech</h2><p>Black Friday, January Sales, and end-of-financial-year clearance (March).</p>''')+'<a href=/ class=bl><- Back to Coupn</a>'),
  ('boots-offers.html', 'Boots UK Offers & Discount Codes | Coupn',
   'Find the latest Boots UK offers and Advantage Card deals. Save on beauty and pharmacy.',
   'Boots offers UK, Boots discount codes, Advantage Card, No7 deals',
   h2('Boots Offers - Beauty Savings','')+cd('''<h2>Latest Boots UK Offers - May 2026</h2><p>Boots Advantage Card: earn 4 points per 1 (up to 10x on selected). 100 points = 1.</p><ul><li><strong>3 for 2</strong> - Selected skincare and beauty</li><li><strong>No7</strong> - Regular 3 for 2</li><li><strong>Student Discount</strong> - 10% off with UNiDAYS</li></ul>''')+'<a href=/ class=bl><- Back to Coupn</a>'),
  ('sainsburys-vouchers.html', "Sainsbury's UK Vouchers & Nectar Deals | Coupn",
   "Best Sainsbury's UK vouchers and Nectar card deals. Save on groceries and Tu clothing.",
   "Sainsbury's vouchers, Nectar deals, Sainsbury's discounts, Tu clothing",
   h2("Sainsbury's Vouchers - Nectar Savings",'')+cd('''<h2>Latest Sainsbury's UK Deals - May 2026</h2><p>Nectar: 1 point per 1. Exchange for money off or use with eBay, Argos, BA.</p><ul><li><strong>Nectar Prices</strong> - Save up to 30%</li><li><strong>Tu Clothing</strong> - Up to 40% off</li><li><strong>Fuel Save</strong> - Exchange points for fuel</li><li><strong>Taste the Difference</strong> - 2 for 7 meals</li></ul><div class=inf>Load personalised offers via the Nectar app before shopping.</div>''')+'<a href=/ class=bl><- Back to Coupn</a>'),
  ('nike-discounts.html', 'Nike UK Discount Codes & Sportswear Deals | Coupn',
   'Find Nike UK discount codes and student offers. Save on trainers and clothing.',
   'Nike discount codes UK, Nike student discount, Nike trainers deals',
   h2('Nike Discounts - Sportswear Savings','')+cd('''<h2>Latest Nike UK Discount Codes - May 2026</h2><ul><li><strong>Student Discount</strong> - 25% off full-price via Student Beans</li><li><strong>Nike Member</strong> - Free delivery + early sale access</li><li><strong>Sale Section</strong> - Up to 40% off at outlet.nike.com</li></ul><h2>How to Save</h2><p>End-of-season sales in January and July. Nike Membership is free. Student discount works on most products.</p>''')+'<a href=/ class=bl><- Back to Coupn</a>'),
  ('booking-com-promos.html', 'Booking.com UK Promo Codes & Hotel Deals | Coupn',
   'Latest Booking.com UK promo codes and Genius discounts. Save on UK hotels and holidays.',
   'Booking.com promo codes, hotel deals UK, Booking.com Genius discount',
   h2('Booking.com Promos - Travel Savings','')+cd('''<h2>Latest Booking.com UK Promo Codes - May 2026</h2><h3>Genius Programme</h3><ul><li><strong>Level 1</strong> - 10% off after 2 bookings</li><li><strong>Level 2</strong> - 15% off plus free breakfast</li><li><strong>Level 3</strong> - 20% off (invite only)</li></ul><h3>Current Deals</h3><ul><li><strong>UKDEAL10</strong> - 10% off UK hotels, min 100</li><li><strong>Free cancellation</strong> - Most bookings</li><li><strong>Pay at hotel</strong> - No upfront</li></ul>''')+'<a href=/ class=bl><- Back to Coupn</a>'),
  ('just-eat-vouchers.html', 'Just Eat UK Voucher Codes & Takeaway Deals | Coupn',
   'Find verified Just Eat UK voucher codes and takeaway deals. Save on food delivery.',
   'Just Eat voucher codes, takeaway deals UK, Just Eat discount, food delivery',
   h2('Just Eat Vouchers - Takeaway Savings','')+cd('''<h2>Latest Just Eat UK Voucher Codes - May 2026</h2><ul><li><strong>Free delivery</strong> - Orders over 15</li><li><strong>New customer</strong> - Up to 50% off first order (max 10)</li><li><strong>Just Eat Plus</strong> - Free delivery, 5.99/month</li><li><strong>Collection</strong> - Save up to 20%</li></ul><h2>Best Time to Order</h2><p>Many restaurants offer lunchtime discounts. Ordering outside peak hours (6-8pm) means faster delivery.</p>''')+'<a href=/ class=bl><- Back to Coupn</a>'),
]


# toolstack.uk - calculators with interactive JS
def calc(slug, title, desc, keywords, icon, calc_html, calc_js, rates):
  main = f'<div class=hero><h2>{icon} {title}</h2><p>{desc}</p></div><div class=co>'
  main += f'<div class=cd><h2>Try Our {title}</h2><div class=cb>{calc_html}<div class=cr id=r></div></div>'
  main += f'<h2>UK Rates (2026/27)</h2><table><tr><th>Category</th><th>Rate</th></tr>'
  for r in rates: main += f'<tr><td>{r[0]}</td><td>{r[1]}</td></tr>'
  main += '</table></div><div class=cd>'
  main += f'<h2>Why Use Our {title}?</h2><ul><li>Free - no sign-up</li><li>Updated for 2026/27</li><li>Instant results</li><li>Works on all devices</li><li>Privacy-first - runs in browser</li></ul>'
  main += '</div><a href=/ class=bl><- Back to ToolStack</a></div>'
  if calc_js: main += f'<script>{calc_js}</script>'
  return (slug, title, desc, keywords, main)

mortgage_js = '''
function m(){var p=parseFloat(document.getElementById('mp').value)||0;var d=parseFloat(document.getElementById('md').value)||0;var r=(parseFloat(document.getElementById('mr').value)||0)/100/12;var n=(parseFloat(document.getElementById('mt').value)||0)*12;var l=p-d;if(l<=0||r<=0||n<=0){return}var m=l*r*Math.pow(1+r,n)/(Math.pow(1+r,n)-1);document.getElementById('r').innerHTML='Monthly: &pound;'+m.toFixed(2)+'<br>Total: &pound;'+(m*n).toFixed(2)+'<br>Interest: &pound;'+(m*n-l).toFixed(2);document.getElementById('r').style.display='block'}m()'''
TOOLS = [
  calc('mortgage-calculator.html', 'Mortgage Calculator', 'Estimate monthly repayments for your UK mortgage.', 'UK mortgage calculator, mortgage repayment, property UK, buying a home UK', '🏠',
    '<label>Price (&pound;)</label><input type=number id=mp value=300000><label>Deposit (&pound;)</label><input type=number id=md value=45000><label>Rate (%)</label><input type=number id=mr value=4.5 step=0.1><label>Term (yrs)</label><input type=number id=mt value=25><button onclick=m()>Calculate</button>',
    mortgage_js,
    [('Avg 2yr fix','4.5-5.5%'),('Avg 5yr fix','4.2-5.0%'),('FTB deposit','5-15%'),('Stamp Duty threshold','250k (425k FTB)')]),
  calc('vat-calculator.html', 'VAT Calculator', 'Add or remove VAT at 20% standard UK rate.', 'UK VAT calculator, 20% VAT, add VAT, remove VAT, gross to net', '🧾',
    '<label>Amount (&pound;)</label><input type=number id=va value=100><label>Rate (%)</label><select id=vr><option value=20>20%</option><option value=5>5% Reduced</option><option value=0>0% Zero</option></select><button onclick=v()>Calculate</button>',
    'function v(){var a=parseFloat(document.getElementById("va").value)||0;var r=parseFloat(document.getElementById("vr").value)/100;var n=a/(1+r);document.getElementById("r").innerHTML="Net: &pound;"+n.toFixed(2)+"<br>VAT: &pound;"+(a-n).toFixed(2)+"<br>Gross: &pound;"+a.toFixed(2);document.getElementById("r").style.display="block"}v()',
    [('Standard','20%'),('Reduced','5%'),('Zero','0%'),('Threshold','90,000')]),
  calc('salary-calculator.html', 'Salary Calculator', 'Calculate take-home pay after tax, NI and pension in the UK.', 'salary calculator UK, take-home pay, income tax UK, NI calculator 2026', '💷',
    '<label>Annual Salary (&pound;)</label><input type=number id=sa value=35000><label>Pension (%)</label><input type=number id=sp value=5><button onclick=s()>Calculate</button>',
    'function s(){var s=parseFloat(document.getElementById("sa").value)||0;var p=parseFloat(document.getElementById("sp").value)/100||0;var pa=12570;var t=Math.max(0,s*(1-p)-pa);var tax=0;if(t>0){var r=50270-pa;tax=Math.min(t,r)*0.2+Math.max(0,t-r)*0.4}var ni=Math.max(0,(Math.min(50270,s)-12570)*0.08+Math.max(0,s-50270)*0.02);var pen=s*p;var net=s-tax-ni-pen;var d=document.getElementById("r");d.innerHTML="Gross: &pound;"+s.toFixed(2)+"<br>Tax: &pound;"+tax.toFixed(2)+"<br>NI: &pound;"+ni.toFixed(2)+"<br>Pension: &pound;"+pen.toFixed(2)+"<br><strong>Net: &pound;"+net.toFixed(2)+"</strong><br>Monthly: &pound;"+(net/12).toFixed(2);d.style.display="block"}s()',
    [('Personal Allowance','12,570'),('Basic Rate','20% (12,571-50,270)'),('Higher Rate','40% (50,271-125,140)'),('NI Main Rate','8% (12,570-50,270)')]),
  calc('bmi-calculator.html', 'BMI Calculator', 'Calculate your Body Mass Index, a measure of body fat based on height and weight.', 'BMI calculator UK, body mass index, healthy weight, NHS BMI', '⚕️',
    '<label>Weight (kg)</label><input type=number id=w value=75><label>Height (cm)</label><input type=number id=h value=175><button onclick=b()>Calculate</button>',
    'function b(){var w=parseFloat(document.getElementById("w").value)||0;var hm=parseFloat(document.getElementById("h").value)/100||1;var bmi=w/(hm*hm);var cat=bmi<18.5?"Underweight":bmi<25?"Healthy":bmi<30?"Overweight":"Obese";document.getElementById("r").innerHTML="BMI: "+bmi.toFixed(1)+"<br>Category: "+cat;document.getElementById("r").style.display="block"}b()',
    [('Underweight','< 18.5'),('Healthy','18.5-24.9'),('Overweight','25.0-29.9'),('Obese','30.0+')]),
  calc('savings-calculator.html', 'Savings Calculator', 'Project your savings growth with compound interest. UK rates updated for 2026.', 'savings calculator UK, compound interest, ISA calculator, savings growth', '🏦',
    '<label>Initial (&pound;)</label><input type=number id=si value=1000><label>Monthly (&pound;)</label><input type=number id=sm value=100><label>Rate (%)</label><input type=number id=sr value=3.5 step=0.1><label>Years</label><input type=number id=sy value=10><button onclick=c()>Calculate</button>',
    'function c(){var i=parseFloat(document.getElementById("si").value)||0;var m=parseFloat(document.getElementById("sm").value)||0;var r=(parseFloat(document.getElementById("sr").value)||0)/100/12;var n=(parseFloat(document.getElementById("sy").value)||0)*12;var f=i*Math.pow(1+r,n)+m*((Math.pow(1+r,n)-1)/r);var d=i+m*n;document.getElementById("r").innerHTML="Final: &pound;"+f.toFixed(2)+"<br>Deposited: &pound;"+d.toFixed(2)+"<br>Interest: &pound;"+(f-d).toFixed(2);document.getElementById("r").style.display="block"}c()',
    [('Best Easy Access','3.5% (May 2026)'),('Best 1yr Fix','4.2%'),('Cash ISA','3.8% avg'),('Lifetime ISA','25% bonus up to 4k/yr')]),
  calc('car-loan-calculator.html', 'Car Loan Calculator', 'Calculate monthly payments on a UK car loan. See total cost including interest.', 'car loan calculator UK, vehicle finance, PCP calculator, APR car loan', '🚗',
    '<label>Car Price (&pound;)</label><input type=number id=cp value=15000><label>Deposit (&pound;)</label><input type=number id=cd value=2000><label>APR (%)</label><input type=number id=cr value=6.9 step=0.1><label>Term (mths)</label><input type=number id=ct value=48><button onclick=l()>Calculate</button>',
    'function l(){var p=parseFloat(document.getElementById("cp").value)||0;var d=parseFloat(document.getElementById("cd").value)||0;var r=(parseFloat(document.getElementById("cr").value)||0)/100/12;var n=parseFloat(document.getElementById("ct").value)||1;var l=p-d;if(l<=0){return}var m=l*r*Math.pow(1+r,n)/(Math.pow(1+r,n)-1);document.getElementById("r").innerHTML="Monthly: &pound;"+m.toFixed(2)+"<br>Total: &pound;"+(m*n+ d).toFixed(2)+"<br>Interest: &pound;"+(m*n-l).toFixed(2);document.getElementById("r").style.display="block"}l()',
    [('Avg used car APR','6.9%'),('New car APR','4.5-7.9%'),('PCP typical','3.9-8.9%'),('Bank loan','3.0-6.0%')]),
  calc('ni-calculator.html', 'NI Calculator', 'Calculate your National Insurance contributions for the 2026/27 tax year.', 'NI calculator UK, National Insurance, Class 1 contributions, UK tax', '📊',
    '<label>Annual Salary (&pound;)</label><input type=number id=na value=35000><button onclick=n()>Calculate</button>',
    'function n(){var s=parseFloat(document.getElementById("na").value)||0;var pt=s>12570?Math.min(50270,s)-12570:0;var ht=s>50270?s-50270:0;var ni=pt*0.08+ht*0.02;var rate=ni>0?(ni/s*100).toFixed(1):0;document.getElementById("r").innerHTML="NI due: &pound;"+ni.toFixed(2)+"<br>Effective rate: "+rate+"%";document.getElementById("r").style.display="block"}n()',
    [('Primary threshold','12,570/yr'),('Upper threshold','50,270/yr'),('Main rate','8%'),('Higher rate','2%')]),
  calc('student-loan-calculator.html', 'Student Loan Calculator', 'Estimate your monthly student loan repayments and total owed.', 'student loan calculator UK, Plan 2, Plan 5, SLC repayment, student finance', '🎓',
    '<label>Salary (&pound;)</label><input type=number id=st value=30000><label>Loan Balance (&pound;)</label><input type=number id=sb value=50000><label>Plan</label><select id=sp><option value=2>Plan 2</option><option value=5>Plan 5</option></select><button onclick=u()>Calculate</button>',
    'function u(){var s=parseFloat(document.getElementById("st").value)||0;var b=parseFloat(document.getElementById("sb").value)||0;var p=parseInt(document.getElementById("sp").value);var th=p==2?27295:25000;var rt=p==2?0.09:0.09;var a=s>th?(s-th)*rt:0;var f=b;for(var y=0;y<30;y++){f=f*1.0325-a;if(f<0)f=0}document.getElementById("r").innerHTML="Monthly: &pound;"+a.toFixed(2)+"/yr<br>30yr projection: &pound;"+f.toFixed(2)+" remaining"+((f==0)?" (PAID OFF)":"");document.getElementById("r").style.display="block"}u()',
    [('Plan 2 threshold','27,295/yr'),('Plan 5 threshold','25,000/yr'),('Repayment rate','9% above threshold'),('Write-off','30 years')]),
  calc('fuel-cost-calculator.html', 'Fuel Cost Calculator', 'Calculate fuel costs for UK journeys. Estimate petrol or diesel cost per trip.', 'fuel cost calculator UK, petrol cost, diesel cost, MPG calculator, journey cost', '⛽',
    '<label>Distance (miles)</label><input type=number id=fd value=200><label>MPG</label><input type=number id=fm value=40><label>Fuel Price (&pound;/L)</label><input type=number id=fp value=1.45 step=0.01><button onclick=f()>Calculate</button>',
    'function f(){var d=parseFloat(document.getElementById("fd").value)||0;var mpg=parseFloat(document.getElementById("fm").value)||1;var p=parseFloat(document.getElementById("fp").value)||0;var gal=d/mpg;var lit=gal*4.54609;var cost=lit*p;document.getElementById("r").innerHTML="Litre required: "+lit.toFixed(1)+"<br>Fuel cost: &pound;"+cost.toFixed(2)+"<br>Per mile: &pound;"+(cost/d).toFixed(2);document.getElementById("r").style.display="block"}f()',
    [('Avg petrol price','145.0p/L'),('Avg diesel price','148.0p/L'),('Avg car MPG','40-50'),('EV cost','3-5p/mile')]),
  calc('discount-calculator.html', 'Discount Calculator', 'Calculate the final price after a percentage discount. Perfect for UK sale shopping.', 'discount calculator UK, percentage off, sale price, savings calculator, shopping', '💰',
    '<label>Original Price (&pound;)</label><input type=number id=do value=100><label>Discount (%)</label><input type=number id=dd value=20><button onclick=d()>Calculate</button>',
    'function d(){var o=parseFloat(document.getElementById("do").value)||0;var dis=parseFloat(document.getElementById("dd").value)||0;var s=o*dis/100;var f=o-s;document.getElementById("r").innerHTML="You save: &pound;"+s.toFixed(2)+"<br>Final price: &pound;"+f.toFixed(2);document.getElementById("r").style.display="block"}d()',
    [('Typical sale','20-50% off'),('Black Friday','Up to 70%'),('Student discount','10-25%')]),
]


# uk-cbdc.co.uk content
CBDC = [
  ('what-is-cbdc.html', 'What is CBDC? Digital Pound Explained UK | uk-cbdc',
   'Learn what a Central Bank Digital Currency (CBDC) is and how the digital pound could work in the UK. Explained simply.',
   'CBDC explained, digital pound UK, central bank digital currency, UK CBDC, digital sterling',
   h2('What is CBDC?', 'Understanding the digital pound and how it could transform UK finance')+cd('''<h2>The Digital Pound Explained</h2><p>A Central Bank Digital Currency (CBDC) is a digital form of a country's fiat currency, issued and backed by the central bank. In the UK, the Bank of England and HM Treasury are exploring the "digital pound" - a UK CBDC that would exist alongside cash and bank deposits.</p><h3>Key Features of a UK CBDC</h3><ul><li><strong>Government-backed</strong> - Unlike crypto, CBDCs are issued by the central bank</li><li><strong>Digital wallet</strong> - Hold digital pounds in a secure digital wallet</li><li><strong>Programmable</strong> - Could enable smart contracts and automated payments</li><li><strong>Privacy-focused</strong> - Designed with data protection in mind</li><li><strong>Offline capability</strong> - May work without internet connection</li></ul><h2>Why Does the UK Need a CBDC?</h2><p>As cash usage declines and digital payments grow, a CBDC would ensure continued access to central bank money. It could also improve payment efficiency, reduce fraud, and enable new financial services.</p><div class=ib>The Bank of England's consultation on the digital pound closed in 2024. A decision on whether to proceed is expected by 2026.</div>''')),
  ('bitcoin-guide.html', 'Bitcoin Guide UK 2026 - How to Buy, Sell & Store BTC',
   'Complete guide to Bitcoin in the UK. How to buy, sell, store and pay tax on Bitcoin. Updated for 2026.',
   'Bitcoin UK guide, buy Bitcoin UK, Bitcoin wallet, Bitcoin tax UK, cryptocurrency guide',
   h2('Bitcoin Guide UK 2026','Everything UK residents need to know about Bitcoin')+cd('''<h2>What is Bitcoin?</h2><p>Bitcoin is the world's first decentralised cryptocurrency, created in 2009 by the pseudonymous Satoshi Nakamoto. It operates on a peer-to-peer network without central authority, using blockchain technology to record transactions.</p><h3>How to Buy Bitcoin in the UK</h3><ol><li><strong>Choose an exchange</strong> - Coinbase, Kraken, Binance (via Binance.US) or UK-based Ziglu</li><li><strong>Verify your identity</strong> - Provide photo ID and proof of address</li><li><strong>Deposit funds</strong> - Bank transfer, debit card, or faster payments</li><li><strong>Buy Bitcoin</strong> - Choose amount and confirm purchase</li></ol><h2>How to Store Bitcoin Safely</h2><p>Hot wallets (apps) are convenient for small amounts. Cold wallets (hardware) are essential for significant holdings. Never keep large amounts on exchanges.</p><h2>Bitcoin Tax in the UK</h2><p>HMRC treats Bitcoin as property, not currency. You pay Capital Gains Tax when selling, spending, or trading crypto. The first 3,000 of gains per year (2026/27 allowance) is tax-free.</p><div class=wb>Always consult a qualified tax advisor for your specific circumstances.</div>''')),
  ('ethereum-guide.html', 'Ethereum Guide UK - ETH, Smart Contracts & DeFi Explained',
   'Complete guide to Ethereum for UK users. Learn about ETH, smart contracts, staking and dApps.',
   'Ethereum UK guide, ETH staking, smart contracts, Ethereum 2.0, dApps UK',
   h2('Ethereum Guide UK','Understanding ETH, smart contracts and the Ethereum ecosystem')+cd('''<h2>What is Ethereum?</h2><p>Ethereum is the world's leading smart contract blockchain. Launched in 2015, it supports decentralised applications (dApps), DeFi protocols, and NFTs. ETH is the native cryptocurrency used to pay transaction fees.</p><h3>Key Features</h3><ul><li><strong>Smart Contracts</strong> - Self-executing code on the blockchain</li><li><strong>Proof of Stake</strong> - Ethereum transitioned in 2022, reducing energy use by 99.9%</li><li><strong>Layer 2 Scaling</strong> - Arbitrum, Optimism, Base make transactions cheap and fast</li><li><strong>DeFi Ecosystem</strong> - Lending, borrowing, trading without intermediaries</li></ul><h2>Staking ETH in the UK</h2><p>Minimum 32 ETH to run a validator node, or stake any amount via exchanges and staking pools. Current staking yield is approximately 3-5% APR. Staking rewards are taxable as income.</p>''')),
  ('crypto-tax-uk.html', 'Crypto Tax UK 2026 - Complete Guide to HMRC & Capital Gains',
   'Everything UK crypto investors need to know about tax. CGT allowance, reporting, allowances and HMRC guidance.',
   'crypto tax UK, HMRC crypto tax, CGT crypto, crypto tax calculator UK, DeFi tax',
   h2('Crypto Tax UK 2026','Navigate HMRC rules on cryptocurrency taxation')+cd('''<h2>How HMRC Taxes Crypto</h2><p>HMRC classifies cryptocurrency as property, not currency or security. This means you pay Capital Gains Tax (CGT) on disposals and Income Tax on certain crypto activities.</p><h3>Taxable Events</h3><ul><li>Selling crypto for fiat currency (GBP)</li><li>Swapping one crypto for another</li><li>Using crypto to pay for goods or services</li><li>Gifting crypto (except to spouse)</li></ul><h3>2026/27 Allowances & Rates</h3><ul><li><strong>CGT allowance</strong> - 3,000 (reduced from previous years)</li><li><strong>Basic rate</strong> - 10% on gains within basic rate band</li><li><strong>Higher rate</strong> - 20% on gains above basic rate band</li><li><strong>Airdrops</strong> - Taxed as income at market value</li></ul><h2>Crypto Tax Calculators</h2><p>Several UK-specific tools can help: Koinly, Recap, and CoinTracking all support HMRC reporting standards.</p>''')),
  ('defi-explained.html', 'DeFi Explained UK - Decentralised Finance Guide 2026',
   'Learn about DeFi, decentralised exchanges, lending protocols and yield farming. UK-focused guide.',
   'DeFi explained, decentralised finance, DeFi UK, yield farming, liquidity pools, DeFi risks',
   h2('DeFi Explained','Understanding decentralised finance and how it works')+cd('''<h2>What is DeFi?</h2><p>Decentralised Finance (DeFi) is a system of financial applications built on blockchain networks, primarily Ethereum. It allows lending, borrowing, trading and earning interest without traditional intermediaries like banks.</p><h3>Key DeFi Services</h3><ul><li><strong>Decentralised Exchanges (DEXs)</strong> - Uniswap, Curve, Balancer - trade tokens P2P</li><li><strong>Lending Protocols</strong> - Aave, Compound - earn interest on deposits or borrow assets</li><li><strong>Yield Aggregators</strong> - Yearn, Harvest - auto-compound yields</li><li><strong>Liquid Staking</strong> - Lido, Rocket Pool - stake ETH while staying liquid</li></ul><h2>Risks to Consider</h2><ul><li><strong>Smart contract risk</strong> - Bugs can lead to loss of funds</li><li><strong>Impermanent loss</strong> - Price divergence in liquidity pools</li><li><strong>Regulatory risk</strong>- UK regulations on DeFi are evolving</li></ul><div class=wb>DeFi carries significant risk. Never invest more than you can afford to lose.</div>''')),
  ('nft-guide-uk.html', 'NFT Guide UK - How to Buy, Sell & Create NFTs 2026',
   'Complete UK guide to NFTs. Learn how to buy, sell and create non-fungible tokens. Tax implications included.',
   'NFT guide UK, buy NFTs UK, digital art UK, NFT tax, mint NFTs',
   h2('NFT Guide UK','Everything you need to know about non-fungible tokens')+cd('''<h2>What are NFTs?</h2><p>Non-Fungible Tokens (NFTs) are unique digital assets verified on a blockchain. They represent ownership of digital items like art, music, collectibles, and virtual real estate.</p><h3>How to Buy NFTs in the UK</h3><ol><li>Set up a crypto wallet (MetaMask, WalletConnect)</li><li>Buy ETH on a UK exchange</li><li>Connect wallet to an NFT marketplace (OpenSea, Blur, Rarible)</li><li>Browse, bid or buy directly</li></ol><h2>Creating (Minting) NFTs</h2><p>Minting an NFT turns your digital file into a token on the blockchain. Platforms like OpenSea allow free or low-cost minting. Gas fees vary with network congestion.</p><h2>NFT Tax UK</h2><p>HMRC treats NFTs as property. Buying, selling and trading NFTs may trigger CGT. Creating/selling as a business may incur Income Tax and VAT.</p>''')),
  ('staking-guide.html', 'Crypto Staking Guide UK - Earn Passive Income 2026',
   'How to stake crypto in the UK. Learn about staking rewards, risks, and tax treatment of staking income.',
   'crypto staking UK, ETH staking, staking rewards, passive income crypto, DeFi staking',
   h2('Crypto Staking Guide','Earn passive income by staking your cryptocurrency')+cd('''<h2>What is Staking?</h2><p>Staking is the process of locking up cryptocurrency to support a proof-of-stake blockchain network. In return, you earn rewards in the form of additional tokens. It's like earning interest on a savings account, but with crypto.</p><h3>Popular Staking Coins</h3><ul><li><strong>Ethereum (ETH)</strong> - 3-5% APR via Lido, Rocket Pool, or exchanges</li><li><strong>Solana (SOL)</strong> - 5-7% APR</li><li><strong>Polkadot (DOT)</strong> - 10-14% APR</li><li><strong>Cardano (ADA)</strong> - 3-5% APR</li></ul><h2>Staking in the UK - Tax</h2><p>Staking rewards are generally taxed as income (Income Tax) at your marginal rate. Any subsequent gains from selling staked tokens are subject to CGT. Keep detailed records.</p><div class=wb>Staking involves risk. Validator penalties (slashing) can result in lost funds.</div>''')),
  ('crypto-wallets-uk.html', 'Crypto Wallets UK - Best Hardware & Software Wallets 2026',
   'Find the best crypto wallets for UK users. Compare hardware wallets, software wallets and exchange wallets.',
   'crypto wallet UK, best wallet Bitcoin, hardware wallet, software wallet, MetaMask UK',
   h2('Crypto Wallets UK','Choose the right wallet for your cryptocurrency needs')+cd('''<h2>Types of Crypto Wallets</h2><h3>Hardware Wallets (Cold Storage)</h3><ul><li><strong>Ledger Nano X</strong> - Bluetooth, supports 5,500+ assets, 149</li><li><strong>Trezor Model T</strong> - Touch screen, open source, 179</li><li><strong>SafePal S1</strong> - Affordable option, 50</li></ul><h3>Software Wallets (Hot Wallets)</h3><ul><li><strong>MetaMask</strong> - Most popular, browser extension + mobile</li><li><strong>Coinbase Wallet</strong> - Self-custodial, integrates with Coinbase</li><li><strong>Trust Wallet</strong> - Binance-owned, multi-chain</li></ul><h2>Best Practice for UK Users</h2><p>Use hot wallets for small amounts (under 500). Store significant holdings on hardware wallets. Never share your seed phrase. Consider a multi-signature setup for large amounts.</p>''')),
  ('bitcoin-mining-uk.html', 'Bitcoin Mining UK - Is It Profitable in 2026?',
   'Can you mine Bitcoin in the UK? Electricity costs, hardware, pools, and profitability analysis for 2026.',
   'Bitcoin mining UK, crypto mining, mining profitability, ASIC miner UK, electricity cost mining',
   h2('Bitcoin Mining UK','Is Bitcoin mining still profitable in the UK?')+cd('''<h2>Bitcoin Mining in the UK</h2><p>Bitcoin mining involves using specialised hardware (ASICs) to solve complex mathematical problems and validate transactions. Miners are rewarded with newly created BTC and transaction fees.</p><h3>Can You Mine Profitably in the UK?</h3><p>The UK's average electricity cost of 28p/kWh makes home mining challenging. A modern ASIC miner (e.g., Antminer S19) consumes 3,250W and would cost approximately 2,200/year in electricity alone.</p><h3>Mining Considerations</h3><ul><li><strong>Hardware cost</strong> - 2,000-6,000 for a current-gen ASIC</li><li><strong>Electricity</strong> - 28p/kWh average - check if you have off-peak rates</li><li><strong>Noise</strong> - ASIC miners are loud (75dB+)</li><li><strong>Heat</strong> - Significant heat output - may need ventilation</li><li><strong>Mining pools</strong> - Join a pool like F2Pool, Poolin, or Slush Pool</li></ul><div class=ib>Cloud mining is widely considered a scam. Never invest in hosted mining contracts.</div>''')),
  ('crypto-scams-uk.html', 'Crypto Scams UK - How to Spot & Avoid Investment Fraud',
   'Guide to identifying and avoiding cryptocurrency scams in the UK. Learn about common fraud types and how to stay safe.',
   'crypto scams UK, avoid crypto scams, cryptocurrency fraud, scam warning, UK investor protection',
   h2('Crypto Scams UK','Protect yourself from cryptocurrency fraud')+cd('''<h2>Common Crypto Scams in the UK</h2><h3>1. Investment Scams</h3><p>Fake investment platforms promising guaranteed returns. Often promoted via social media ads featuring celebrity endorsements (deepfakes).</p><h3>2. Romance Scams</h3><p>Scammers build relationships on dating apps over weeks or months, then introduce "crypto investment opportunities" to steal funds.</p><h3>3. Phishing</h3><p>Fake emails, texts or websites pretending to be Coinbase, MetaMask, or your exchange. Always check URLs carefully.</p><h3>4. Pump & Dump Schemes</h3><p>Groups coordinate to buy obscure tokens, inflate price, then sell - leaving late buyers with worthless tokens.</p><h2>How to Stay Safe</h2><ul><li>If it sounds too good to be true, it probably is</li><li>Never share your seed phrase with anyone</li><li>Only use reputable exchanges registered with the FCA</li><li>Verify URLs before entering credentials</li><li>Enable 2FA on all accounts</li></ul><div class=wb>The FCA maintains a warning list of unauthorized firms. Check before investing.</div>''')),
]


# pdfoomph.com content
PDFO = [
  ('merge-pdf.html', 'Merge PDF Files Online Free - Combine PDFs | PDFoomph',
   'Merge multiple PDF files into one document. Free online PDF merger - no upload limits, no sign-up, works in your browser.',
   'merge PDF, combine PDF files, PDF merger, join PDF files, merge PDF online free',
   h2('Merge PDF Files','Combine multiple PDFs into one document')+cd('''<h2>How to Merge PDF Files</h2><p>Our free PDF merger lets you combine multiple PDF files into a single document. No upload required - everything happens in your browser. Unlimited file sizes.</p><ol><li><strong>Select files</strong> - Choose the PDFs you want to combine</li><li><strong>Reorder</strong> - Drag and drop to arrange pages</li><li><strong>Merge</strong> - Combine into one document instantly</li><li><strong>Download</strong> - Get your merged PDF</li></ol><h2>Why Use PDFoomph?</h2><ul><li>Free - no hidden charges</li><li>No sign-up required</li><li>No upload limits</li><li>Secure - files never leave your device</li><li>Works on any device</li></ul>''')),
  ('split-pdf.html', 'Split PDF Files Online Free - Separate Pages | PDFoomph',
   'Split PDF files into multiple documents. Extract pages from PDFs free online. No limits, no sign-up.',
   'split PDF, separate PDF pages, extract PDF pages, split PDF online, PDF page extractor',
   h2('Split PDF Files','Separate pages or extract sections from PDFs')+cd('''<h2>How to Split a PDF</h2><p>Our PDF splitter lets you separate pages from a PDF file into individual documents. Free, secure, and works entirely in your browser.</p><ul><li><strong>Split all pages</strong> - Each page becomes its own PDF</li><li><strong>Extract range</strong> - Choose a specific page range</li><li><strong>Extract selection</strong> - Select specific pages to extract</li></ul><h2>Why Split PDFs?</h2><p>Common uses: extract chapters from eBooks, separate invoice pages, divide large reports, extract specific pages for sharing.</p>''')),
  ('compress-pdf.html', 'Compress PDF Files Online Free - Reduce PDF Size | PDFoomph',
   'Compress PDF files to reduce file size. Free online PDF compressor - shrink large PDFs without losing quality.',
   'compress PDF, reduce PDF size, PDF compressor, shrink PDF, PDF file size reduction',
   h2('Compress PDF Files','Reduce PDF file size while maintaining quality')+cd('''<h2>How to Compress a PDF</h2><p>Reduce your PDF file size with our free compression tool. Perfect for email attachments, website uploads, and saving storage space.</p><h3>Compression Levels</h3><ul><li><strong>Maximum compression</strong> - Smallest file size, lower quality for images</li><li><strong>Balanced</strong> - Good size reduction with minimal quality loss</li><li><strong>Lossless</strong> - No quality loss, moderate size reduction</li></ul><h2>When to Compress PDFs</h2><ul><li>Sending documents via email (most providers limit to 25MB)</li><li>Uploading to websites or portals</li><li>Saving storage space on your device</li><li>Faster sharing and downloading</li></ul>''')),
  ('jpg-to-pdf.html', 'Convert JPG to PDF Online Free - Image to PDF | PDFoomph',
   'Free online JPG to PDF converter. Convert images to PDF in seconds. No limits, no sign-up, works in browser.',
   'JPG to PDF, convert image to PDF, PNG to PDF, picture to PDF, image converter',
   h2('Convert JPG to PDF','Turn your images into PDF documents')+cd('''<h2>How to Convert JPG to PDF</h2><p>Convert your images to PDF documents instantly. No upload needed - processing happens in your browser. Supports JPG, PNG, GIF, BMP and WEBP.</p><ol><li><strong>Upload images</strong> - Select from your device</li><li><strong>Arrange</strong> - Reorder images if creating a multi-page PDF</li><li><strong>Convert</strong> - Your PDF is generated instantly</li><li><strong>Download</strong> - Save your new PDF document</li></ol><h2>Common Uses</h2><ul><li>Turn scanned documents into PDFs</li><li>Create photo albums as PDFs</li><li>Combine multiple images for sharing</li><li>Convert receipts and invoices</li></ul>''')),
  ('pdf-to-word.html', 'Convert PDF to Word Online Free - PDF to DOCX | PDFoomph',
   'Free online PDF to Word converter. Convert PDF files to editable Word documents. No upload limits.',
   'PDF to Word, convert PDF to DOCX, PDF to editable document, PDF converter',
   h2('Convert PDF to Word','Turn PDFs into editable Word documents')+cd('''<h2>How to Convert PDF to Word</h2><p>Our free converter turns PDF files into editable Word (DOCX) documents. Perfect for revising contracts, editing resumes, or extracting text.</p><ul><li><strong>Preserves layout</strong> - Original formatting maintained</li><li><strong>Extracts images</strong> - Images transfer to Word</li><li><strong>Recognises tables</strong> - Tables become editable Word tables</li><li><strong>OCR support</strong> - Scanned documents can be converted (selected plans)</li></ul>''')),
  ('pdf-to-excel.html', 'Convert PDF to Excel Online Free - PDF to XLSX | PDFoomph',
   'Free online PDF to Excel converter. Extract data from PDF tables into editable spreadsheets.',
   'PDF to Excel, convert PDF to XLSX, PDF to spreadsheet, extract PDF table, data extraction',
   h2('Convert PDF to Excel','Extract tables and data from PDFs into spreadsheets')+cd('''<h2>How to Convert PDF to Excel</h2><p>Convert PDF tables and data into editable Excel spreadsheets. Perfect for financial reports, invoices, and data extraction.</p><ul><li><strong>Table recognition</strong> - Automatically detects and converts tables</li><li><strong>Data accuracy</strong> - Preserves numbers, dates and formatting</li><li><strong>Multiple sheets</strong> - Handles multi-page PDFs</li></ul>''')),
  ('password-protect-pdf.html', 'Password Protect PDF Online Free - Secure PDFs | PDFoomph',
   'Add password protection to PDF files. Free online PDF encryption. Secure your sensitive documents.',
   'password protect PDF, PDF encryption, secure PDF, add password to PDF, PDF security',
   h2('Password Protect PDF','Secure your PDF documents with encryption')+cd('''<h2>How to Password Protect a PDF</h2><p>Add strong password protection to your PDF files. Uses AES-256 encryption - the industry standard for document security.</p><ol><li><strong>Upload PDF</strong> - Select the file to protect</li><li><strong>Set password</strong> - Choose a strong password</li><li><strong>Encrypt</strong> - Your PDF is protected instantly</li><li><strong>Download</strong> - Get your encrypted PDF</li></ol><div class=inf>Use a strong password with at least 8 characters, mixing letters, numbers and symbols.</div>''')),
  ('unlock-pdf.html', 'Unlock PDF Online Free - Remove Password | PDFoomph',
   'Remove password protection from PDF files. Free online PDF unlocker - unlock secured PDFs instantly.',
   'unlock PDF, remove PDF password, PDF password remover, decrypt PDF, remove PDF security',
   h2('Unlock PDF','Remove password protection from your PDFs')+cd('''<h2>How to Unlock a PDF</h2><p>Remove password protection from PDF files that you have the password for. This tool is for unlocking your own documents.</p><div class=wb>Only unlock PDFs that you own or have permission to modify. Removing protection from copyrighted material may breach terms.</div><ul><li><strong>Opens permission-restricted</strong> - Removes printing, editing and copying restrictions</li><li><strong>Password removal</strong> - Remove open-password from PDFs</li><li><strong>Batch unlock</strong> - Process multiple files</li></ul>''')),
  ('rotate-pdf.html', 'Rotate PDF Pages Online Free | PDFoomph',
   'Rotate PDF pages to the correct orientation. Free online PDF rotator - rotate single pages or entire documents.',
   'rotate PDF, rotate PDF pages, PDF page orientation, flip PDF, PDF editor',
   h2('Rotate PDF Pages','Fix page orientation in your PDF documents')+cd('''<h2>How to Rotate a PDF</h2><p>Fix upside-down or incorrectly oriented pages in your PDF files. Rotate individual pages or the entire document.</p><ul><li><strong>Rotate clockwise</strong> - 90 degrees right</li><li><strong>Rotate anticlockwise</strong> - 90 degrees left</li><li><strong>Flip 180</strong> - Turn completely upside-down</li></ul><h2>Common Uses</h2><ul><li>Fix scanned documents with mixed orientations</li><li>Correct photos embedded in PDFs</li><li>Standardise multi-page landscape/portrait mixes</li></ul>''')),
  ('word-to-pdf.html', 'Convert Word to PDF Online Free - DOCX to PDF | PDFoomph',
   'Free online Word to PDF converter. Convert DOCX and DOC files to PDF format instantly.',
   'Word to PDF, DOCX to PDF, convert Word document, DOC to PDF, file converter',
   h2('Convert Word to PDF','Turn Word documents into professional PDFs')+cd('''<h2>How to Convert Word to PDF</h2><p>Convert your Word documents to PDF format for professional sharing. Perfect for CVs, reports, and formal documents.</p><ul><li><strong>Preserves formatting</strong> - Fonts, styles and images stay intact</li><li><strong>Smaller files</strong> - PDFs are often smaller than source DOCX</li><li><strong>Universal</strong> - PDFs look the same on any device</li></ul><h2>Why Convert Word to PDF?</h2><ul><li>Ensures consistent formatting across devices</li><li>Prevents accidental edits</li><li>Smaller file size for email</li><li>Professional appearance</li></ul>''')),
]


# isitdownrightnow.co.uk content
ISDN = []
for svc in [('Spotify','spotify.com','Music streaming','spotify-down.html'),
            ('Netflix','netflix.com','Streaming TV','netflix-down.html'),
            ('WhatsApp','whatsapp.com','Messaging','whatsapp-down.html'),
            ('Instagram','instagram.com','Social media','instagram-down.html'),
            ('YouTube','youtube.com','Video sharing','youtube-down.html'),
            ('Twitter / X','x.com','Social media','twitter-down.html'),
            ('Google','google.com','Search engine','google-down.html'),
            ('Gmail','gmail.com','Email','gmail-down.html'),
            ('Reddit','reddit.com','Social news','reddit-down.html'),
            ('Facebook','facebook.com','Social network','facebook-down.html')]:
  name,domain,cat,slug = svc
  ISDN.append((slug, f'Is {name} Down Right Now? Check {name} Status | IsItDownRightNow',
    f'Check if {name} is down for everyone or just you. Real-time {name} outage status. UK users check {name} server status here.',
    f'{name} down, {name} status, {name} outage, is {name} down UK, {name} not working',
    h2(f'Is {name} Down?','Check real-time status')+cd(f'''<h2>{name} Status Check</h2><p>Wondering if {name} is down? We check the current status of {name} so you can see if it's a widespread outage or a local issue.</p><h3>Common Issues with {name}</h3><ul><li><strong>Server outages</strong> - {name} occasionally experiences downtime during maintenance</li><li><strong>DNS issues</strong> - Problems resolving the {name} domain</li><li><strong>App crashes</strong> - Mobile app may freeze or fail to load</li><li><strong>Slow loading</strong> - Pages take long to load or time out</li></ul><h2>What to Do If {name} Is Down</h2><ol><li>Check other websites - if others work, it might be {name} specific</li><li>Restart your router and devices</li><li>Clear your browser cache and cookies</li><li>Try accessing via mobile data instead of WiFi</li><li>Check {name}'s official status page or social media for updates</li></ol><div class=inf>Most outages resolve within 30 minutes. For prolonged downtime, check the service's official support channels.</div>''')))

