// ─────────────────────────────────────────
export const DEALS = [
  {
    id: '1',
    emoji: '☕',
    title: 'Free Pastry with Any Coffee',
    shop: 'The Coffee Spot',
    address: '12 High Street, NW10',
    category: 'Food & Drink',
    type: 'Flash Sale',
    desc: 'Grab any hot or iced coffee today and get a free pastry on us. Fresh croissants and muffins. Today only — while stocks last. Show this screen at the counter.',
    distance: '0.2mi',
    distanceNum: 0.2,
    timerSecs: 2832,
    redemptions: 6,
    urgency: 'high',
    lat: 51.5322,
    lng: -0.2356,
    bgColor: '#1a0f00',
  },
  {
    id: '2',
    emoji: '✂️',
    title: '50% Off All Haircuts',
    shop: 'Blades Barbers',
    address: '8 Market Lane, NW10',
    category: 'Beauty',
    type: 'Flash Sale',
    desc: 'Flash sale on all cuts — buzz, fade, or full style. No appointment needed. Just walk in and mention Out & About at the till.',
    distance: '0.4mi',
    distanceNum: 0.4,
    timerSecs: 4324,
    redemptions: 3,
    urgency: 'medium',
    lat: 51.5318,
    lng: -0.2341,
    bgColor: '#0a1a0a',
  },
  {
    id: '3',
    emoji: '🍕',
    title: 'Buy 1 Get 1 Free Pizza Slices',
    shop: 'Slice & Dice',
    address: '22 High Street, NW10',
    category: 'Food & Drink',
    type: 'Happy Hour',
    desc: 'Happy hour is on. Buy any slice and get the next one free. Mix and match toppings. Show this screen at the counter.',
    distance: '0.6mi',
    distanceNum: 0.6,
    timerSecs: 13500,
    redemptions: 11,
    urgency: 'low',
    lat: 51.5310,
    lng: -0.2370,
    bgColor: '#0d0d1a',
  },
  {
    id: '4',
    emoji: '💆',
    title: '30% Off All Treatments',
    shop: 'Serenity Beauty',
    address: '5 Park Road, NW10',
    category: 'Beauty',
    type: 'Today Only',
    desc: 'Book any treatment today and get 30% off. Facials, massages, manicures and more. Mention Out & About when you arrive.',
    distance: '0.8mi',
    distanceNum: 0.8,
    timerSecs: 19200,
    redemptions: 4,
    urgency: 'low',
    lat: 51.5330,
    lng: -0.2380,
    bgColor: '#1a0a0a',
  },
  {
    id: '5',
    emoji: '👟',
    title: '20% Off All Footwear',
    shop: 'StepUp Shoes',
    address: '40 High Street, NW10',
    category: 'Retail',
    type: 'Weekend Deal',
    desc: 'Weekend-only deal on our entire footwear range. Trainers, boots, sandals — 20% off everything. No code needed, just show this screen.',
    distance: '1.1mi',
    distanceNum: 1.1,
    timerSecs: 28800,
    redemptions: 9,
    urgency: 'low',
    lat: 51.5305,
    lng: -0.2345,
    bgColor: '#0a0d1a',
  },
];

// ─────────────────────────────────────────
